---
- name: GENERATE A REPORT
  hosts: WAN


  tasks:
    - name: IMPORT ROLE
      import_role:
        name: ansible-network.network-engine

    - name: CAPTURE SHOW NTP
      ios_command:
        commands: show ntp associations detail
      register: ntp

    # - name: DISPLAY THE OUTPUT
    #   debug: 
    #     var: ntp.stdout[0]
     
    - name: SET NTP FACT
      set_fact:
        ntp_fact: "{{ ntp.stdout[0] }}"

    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "/etc/ansible/parsers/show_ntp_associations2.yaml"  
        content: "{{ ntp_fact }}"  # .stdout[0] 
      register: ntp_facts


    # # GUARDA EL CONTINGUT EN UN ARCHIU (FUNCIONA BE)  
    # - name: COPY TO FILE
    #   copy: content="{{ ntp_facts| to_nice_json }}" dest="./templates/{{ inventory_hostname }}_ntp.json"




    - name: GET SIMPLE VALUE
      debug: 
        var: item
      loop: "{{ ansible_facts | json_query('ntp_facts.[*].sanity') }}"

#   json_out: "{{ json_var | json_query('menu.popup.\"dot.key\"[].value') }}"


    # - name: SHOW PARSED RESULT
    #   debug: 
    #     msg: "{{ ntp_facts }}"


    # - name: GET SIMPLE VALUE
    #   debug: 
    #      var: item
    #   loop: "{{ ansible_facts | json_query('ntp.sanity') }}"

    ## GUARDA EL CONTINGUT EN UN ARCHIU (FUNCIONA BE)  
    # - name: COPY TO FILE
    #   copy: content="{{ ntp_dus | to_nice_json }}" dest="./templates/{{ inventory_hostname }}_ntp.json"

    # - name: SHOW PARSED RESULT
    #   debug: 
    #     var: ntp_dus

    # - name: GET SIMPLE VALUE
    #   debug: 
    #      var: item
    #   loop: "{{ ansible_facts | json_query('ntp.sanity') }}"
