---
- name: Create access vlans with ios_l2
  hosts: DC1
  strategy: free
  gather_facts: no


  tasks:
   - name:  create and add vlan to interfaces vlan 50
     ios_l2_interface:
       name: Ethernet0/2
       mode: access
       access_vlan: 50
 

   - name:  create and add vlan to interfaces vlan 40
     ios_l2_interface:
       name: Ethernet0/1
       mode: access
       access_vlan: 40
       
