---
# defaults file for ansible-network.cisco_nxos
#
nxos_config_source:
  running: show running-config
  startup: show startup-config

nxos_get_facts_command_map: "{{ role_path }}/vars/get_facts_command_map.yaml"
nxos_get_facts_subset: "{{ subset | default(['default']) }}"

nxos_config_replace_fs: "{{ replace_fs | default('bootflash:') }}"

nxos_rollback_enabled: "{{ rollback_enabled | default(True) }}"

nxos_config_temp_config_file: "tmp_{{ inventory_hostname_short }}"
nxos_config_remove_temp_files: "{{ remove_temp_files | default(True) }}"
