---
- name: run cli command pre hook
  include_tasks: "{{ nxos_run_cli_command_pre_hook }}"
  when: nxos_run_cli_command_pre_hook is defined and nxos_run_cli_command_pre_hook

- name: run command and parse output
  cli:
    command: "{{ nxos_command }}"
    parser: "{{ parser }}"
    engine: "{{ nxos_parser_engine | default(None) }}"
  with_first_found:
    - files:
        - "{{ nxos_parser }}"
      paths:
        - "{{ playbook_dir }}/parser_templates/nxos"
        - "~/.ansible/ansible_network/parser_templates/nxos"
        - "/etc/ansible/ansible_network/parser_templates/nxos"
        - "{{ role_path }}/parser_templates"
  loop_control:
    loop_var: parser

- name: run cli command post hook
  include_tasks: "{{ nxos_run_cli_command_post_hook }}"
  when: nxos_run_cli_command_post_hook is defined and nxos_run_cli_command_post_hook
