---
# save_config task
#
- name: initialize function
  include_tasks: includes/init.yaml

- name: copy running-config to startup-config
  cli:
    command: "copy running-config startup-config"
  when: not ansible_check_mode
  changed_when: true
